server:
  port: 8761

spring:
  application:
    name: service-registry

eureka:
  client:
    fetchRegistry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

