apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: authservice:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9003
          env:
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: http://eureka-server:8761/eureka/
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9003
            initialDelaySeconds: 40
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  ports:
    - port: 9003
      targetPort: 9003
  selector:
    app: auth-service
