spring:
  application:
    name: NotificationService
  kafka:
    bootstrap-servers: message-broker:29092
    consumer:
        group-id: notification-group
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
         spring.json.trusted.packages: com.example.mail.event
  mail:
    host: smtp.example.com
    port: 2525
    username: test_user
    password: test_password
    properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true
        mail.smtp.ssl.trust: smtp.example.com

server:
  port: 9004

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    db:
      enabled: true
    diskSpace:
      enabled: true
  metrics:
    enable:
      all: true

