spring:
  application:
    name: NotificationService
  kafka:
    bootstrap-servers: message-broker:29092
    consumer:
        group-id: notification-group
        auto-offset-reset: earliest
        key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
        properties:
          spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
          spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
          spring.json.trusted.packages: com.example.user.event
          spring.json.value.default.type: com.example.user.event.UserRegisteredEvent
  mail:
    host: mailpit
    port: 1025

server:
  port: 9004

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    db:
      enabled: true
    diskSpace:
      enabled: true
  metrics:
    enable:
      all: true

